name: Bug report
description: Create a report of your issue
body:
- type: checkboxes
  id: troubleshooting
  attributes:
    label: Have you checked our Troubleshooting page for your issue?
    description: Please read the <a href="https://github.com/Jackett/Jackett/wiki/Troubleshooting">Troubleshooting</a> page for steps to resolve common issues.
    options:
      - label: I have checked the Troubleshooting page
        required: true
- type: checkboxes
  id: already-an-issue
  attributes:
    label: Is there already an issue for your problem?
    description: Please make sure you are not creating an already submitted <a href="https://github.com/Jackett/Jackett/issues">Issue</a>. Check closed issues as well, because your issue may have already been fixed.
    options:
      - label: I have checked older issues, open and closed
        required: true
- type: checkboxes
  id: contributing-guidelines
  attributes:
    label: Have you read our Contributing Guidelines?
    description: Please read our <a href="https://github.com/Jackett/Jackett/blob/master/CONTRIBUTING.md#troubleshooting">Contributing Guidelines (Troubleshooting and Reporting a Bug sections)</a> before submitting your issue to ensure a prompt response to your bug.
    options:
      - label: I have read the Contributing Guidelines
        required: true
- type: input
  attributes:
    label: Have you ACTUALLY checked all these?
    description: Please do not waste our time and yours; these checks are there for a reason, it is not just so you can tick boxes for fun. If you type <b>YES</b> and it is clear you did not or have put in no effort, your issue will be closed and locked without comment. If you type <b>NO</b> but still open this issue, you will be permanently blocked for timewasting.
    placeholder: YES or NO
  validations:
    required: true
- type: textarea
  id: environment
  attributes:
    label: Environment
    description: Please provide the details of the system Jackett is running on. The best way to do this is to restart Jackett, access the dashboard, view the log, and copy/paste replacing the example below with the last 10 Info lines at the bottom of the log.
    placeholder: |
      Using HTTP Client: HttpWebClient/HttpWebClient2
      Using FlareSolverr: Disabled or a url
      Using proxy: Disabled or HTTP/SOCKS4/SOCKS5
      App config/log directory: folder path
      Running in Docker: No/Yes
      Jackett variant: CoreWindows/FullFrameworkWindows/CoreMacOs/CoreLinuxAmdx64/CoreLinuxArm32/CoreLinuxArm64/Mono
      OS version: platform n.nn (32bit/64bit)
      Environment version: n.n.nn (folder path)
      Starting Jackett vn.nn.nn
    render: markdown
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Description
    description: List steps to reproduce the error and details on what happens and what you expected to happen.
  validations:
    required: true
- type: textarea
  id: error-logs
  attributes:
    label: Logged Error Messages
    description: |
      Place any relevant error messages you noticed from the logs here.
      Make sure you attach the full logs with your personal information removed in case we need more information.
    render: text
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: Screenshots
    description: Place any useful screenshots of the issue here, if needed (not a screenshot of the error textbox)
  validations:
    required: false
