import Head from "next/head";

export default function Layout({ children }: React.PropsWithChildren<{}>) {
	return (
		<>
			<Head>
				<title>Jackett</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{children}
		</>
	);
}
