using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;

namespace Jackett.Common.Models.IndexerConfig.Bespoke
{
    [ExcludeFromCodeCoverage]
    internal class ConfigurationDataAvistaZ : ConfigurationDataAvistaZTracker
    {
        public MultiSelectConfigurationItem SearchAudioLanguages { get; private set; }
        public MultiSelectConfigurationItem SearchSubtitleLanguages { get; private set; }
        public DisplayInfoConfigurationItem InfoSearchLanguages { get; private set; }

        public ConfigurationDataAvistaZ()
        {
            SearchAudioLanguages = new MultiSelectConfigurationItem(
                "Search Audio Languages",
                new Dictionary<string, string>
                {
                    { "7", "Arabic" },
                    { "10", "Assamese" },
                    { "17", "Basque" },
                    { "19", "Bengali" },
                    { "23", "Bosnian" },
                    { "189", "Brazilian Portuguese" },
                    { "26", "Burmese" },
                    { "27", "Cantonese" },
                    { "28", "Catalan" },
                    { "29", "Central Khmer" },
                    { "30", "Chamorro" },
                    { "33", "Chinese" },
                    { "39", "Croatian" },
                    { "40", "Czech" },
                    { "41", "Danish" },
                    { "43", "Dutch" },
                    { "44", "Dzongkha" },
                    { "45", "English" },
                    { "46", "Esperanto" },
                    { "188", "Filipino" },
                    { "51", "Finnish" },
                    { "52", "French" },
                    { "58", "German" },
                    { "59", "Greek" },
                    { "61", "Gujarati" },
                    { "63", "Hausa" },
                    { "64", "Hebrew" },
                    { "66", "Hindi" },
                    { "68", "Hungarian" },
                    { "72", "Indonesian" },
                    { "75", "Inuktitut" },
                    { "78", "Italian" },
                    { "79", "Japanese" },
                    { "80", "Javanese" },
                    { "82", "Kannada" },
                    { "84", "Kashmiri" },
                    { "85", "Kazakh" },
                    { "88", "Kirghiz" },
                    { "91", "Korean" },
                    { "94", "Lao" },
                    { "104", "Malay" },
                    { "105", "Malayalam" },
                    { "107", "Mandarin" },
                    { "110", "Marathi" },
                    { "112", "Mongolian" },
                    { "118", "Nepali" },
                    { "123", "Ojibwa" },
                    { "124", "Oriya" },
                    { "127", "Pali" },
                    { "128", "Panjabi" },
                    { "129", "Persian" },
                    { "130", "Polish" },
                    { "131", "Portuguese" },
                    { "133", "Quechua" },
                    { "134", "Romanian" },
                    { "137", "Russian" },
                    { "140", "Sanskrit" },
                    { "146", "Sinhala" },
                    { "147", "Slovak" },
                    { "151", "Spanish" },
                    { "155", "Swedish" },
                    { "156", "Tagalog" },
                    { "159", "Tamil" },
                    { "161", "Telugu" },
                    { "162", "Thai" },
                    { "163", "Tibetan" },
                    { "168", "Turkish" },
                    { "171", "Uighur" },
                    { "172", "Ukrainian" },
                    { "173", "Urdu" },
                    { "176", "Vietnamese" },
                    { "182", "Xhosa" },
                })
            {
                Values = Array.Empty<string>()
            };
            SearchSubtitleLanguages = new MultiSelectConfigurationItem(
                "Search Subtitle Languages",
                new Dictionary<string, string>
                {
                    { "1", "Abkhazian" },
                    { "2", "Afar" },
                    { "3", "Afrikaans" },
                    { "5", "Albanian" },
                    { "6", "Amharic" },
                    { "7", "Arabic" },
                    { "17", "Basque" },
                    { "18", "Belarusian" },
                    { "19", "Bengali" },
                    { "23", "Bosnian" },
                    { "189", "Brazilian Portuguese" },
                    { "25", "Bulgarian" },
                    { "26", "Burmese" },
                    { "27", "Cantonese" },
                    { "28", "Catalan" },
                    { "29", "Central Khmer" },
                    { "32", "Chichewa" },
                    { "33", "Chinese" },
                    { "37", "Corsican" },
                    { "39", "Croatian" },
                    { "40", "Czech" },
                    { "41", "Danish" },
                    { "43", "Dutch" },
                    { "45", "English" },
                    { "46", "Esperanto" },
                    { "47", "Estonian" },
                    { "50", "Fijian" },
                    { "188", "Filipino" },
                    { "51", "Finnish" },
                    { "52", "French" },
                    { "55", "Galician" },
                    { "57", "Georgian" },
                    { "58", "German" },
                    { "59", "Greek" },
                    { "61", "Gujarati" },
                    { "62", "Haitian" },
                    { "64", "Hebrew" },
                    { "66", "Hindi" },
                    { "68", "Hungarian" },
                    { "69", "Icelandic" },
                    { "72", "Indonesian" },
                    { "77", "Irish" },
                    { "78", "Italian" },
                    { "79", "Japanese" },
                    { "80", "Javanese" },
                    { "82", "Kannada" },
                    { "85", "Kazakh" },
                    { "91", "Korean" },
                    { "93", "Kurdish" },
                    { "94", "Lao" },
                    { "95", "Latin" },
                    { "96", "Latvian" },
                    { "99", "Lithuanian" },
                    { "102", "Macedonian" },
                    { "103", "Malagasy" },
                    { "104", "Malay" },
                    { "105", "Malayalam" },
                    { "107", "Mandarin" },
                    { "109", "Maori" },
                    { "110", "Marathi" },
                    { "112", "Mongolian" },
                    { "118", "Nepali" },
                    { "120", "Norwegian" },
                    { "22", "Norwegian Bokmål" },
                    { "124", "Oriya" },
                    { "128", "Panjabi" },
                    { "129", "Persian" },
                    { "130", "Polish" },
                    { "131", "Portuguese" },
                    { "134", "Romanian" },
                    { "135", "Romansh" },
                    { "137", "Russian" },
                    { "141", "Sardinian" },
                    { "142", "Serbian" },
                    { "146", "Sinhala" },
                    { "147", "Slovak" },
                    { "148", "Slovenian" },
                    { "149", "Somali" },
                    { "151", "Spanish" },
                    { "152", "Sundanese" },
                    { "153", "Swahili" },
                    { "155", "Swedish" },
                    { "156", "Tagalog" },
                    { "159", "Tamil" },
                    { "161", "Telugu" },
                    { "162", "Thai" },
                    { "168", "Turkish" },
                    { "170", "Twi" },
                    { "172", "Ukrainian" },
                    { "173", "Urdu" },
                    { "175", "Venda" },
                    { "176", "Vietnamese" },
                    { "177", "Volapük" },
                    { "179", "Welsh" },
                    { "181", "Wolof" },
                })
            {
                Values = Array.Empty<string>()
            };

            InfoSearchLanguages = new DisplayInfoConfigurationItem("Info Search Languages", "The audio and subtitle language settings are AND searches, e.g. selecting English audio with Basque and Catalan subtitles, will only return results with all three of these.");
        }
    }
}
